# Generated by Django 4.2.9 on 2024-02-01 16:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carsAPI', '0003_alter_cars_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='price',
        ),
        migrations.AddField(
            model_name='cars',
            name='adventType',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='тип транспорта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='engine_capacity',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='объём двигателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='engine_type',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='тип двигателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='generation',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='поколение модели'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='locationName',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='населённый пункт продажи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='priceUSD',
            field=models.FloatField(default=1, verbose_name='цена в долларах'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='sellerName',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Имя продавца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='sellerUsername',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='username продавца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='transmition_type',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='тип коробки передач'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='vin',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='вин код ТС'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cars',
            name='brand',
            field=models.TextField(verbose_name='марка машины'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='model',
            field=models.TextField(verbose_name='модель машины'),
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='./static/', verbose_name='сылка на фото')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsAPI.cars')),
            ],
        ),
    ]
